[program:server-panel-horizon]
command=/usr/bin/php /var/www/server-panel/artisan horizon
directory=/var/www/server-panel
user=www-data
autostart=true
autorestart=true
stopwaitsecs=7200
redirect_stderr=true
stdout_logfile=/var/log/server-panel/horizon.log
