<?php

return [
    'modules' => [
        'acl' => [
            'name' => 'User Access Levels',
            'category' => 'Security',
            'description' => 'Panel roles, ownership, and delegated access controls.',
            'packages' => [],
            'services' => [],
            'ports' => [],
        ],
        'websites' => [
            'name' => 'Websites',
            'category' => 'Web',
            'description' => 'Nginx virtual hosts, document roots, SSL, and PHP-FPM routing.',
            'packages' => ['nginx'],
            'services' => ['nginx'],
            'ports' => [80, 443],
        ],
        'ssl' => [
            'name' => 'Auto SSL',
            'category' => 'Web',
            'description' => 'Certbot based certificate renewals and web-server reloads.',
            'packages' => ['certbot', 'python3-certbot-nginx'],
            'services' => ['certbot.timer'],
            'ports' => [80, 443],
        ],
        'dns' => [
            'name' => 'DNS Server',
            'category' => 'DNS',
            'description' => 'PowerDNS authoritative DNS module and zone/record management foundation.',
            'packages' => ['pdns-server', 'pdns-backend-mysql'],
            'services' => ['pdns'],
            'ports' => [53],
        ],
        'databases' => [
            'name' => 'Databases',
            'category' => 'Database',
            'description' => 'MariaDB/MySQL databases, users, and phpMyAdmin package support.',
            'packages' => ['mariadb-server', 'phpmyadmin'],
            'services' => ['mariadb'],
            'ports' => [3306],
        ],
        'ftp' => [
            'name' => 'FTP Server',
            'category' => 'Files',
            'description' => 'Pure-FTPd package/service module and account inventory.',
            'packages' => ['pure-ftpd'],
            'services' => ['pure-ftpd'],
            'ports' => [21],
        ],
        'mail' => [
            'name' => 'Mail Server',
            'category' => 'Email',
            'description' => 'Postfix, Dovecot, OpenDKIM, and Rspamd package/service foundation.',
            'packages' => ['postfix', 'dovecot-imapd', 'dovecot-pop3d', 'opendkim', 'opendkim-tools', 'rspamd'],
            'services' => ['postfix', 'dovecot', 'opendkim', 'rspamd'],
            'ports' => [25, 465, 587, 993, 995],
        ],
        'webmail' => [
            'name' => 'Webmail',
            'category' => 'Email',
            'description' => 'SnappyMail/RainLoop style webmail integration point.',
            'packages' => ['unzip'],
            'services' => [],
            'ports' => [],
        ],
        'email-delivery' => [
            'name' => 'Email Delivery',
            'category' => 'Email',
            'description' => 'Sender policy, DKIM/SPF/DMARC, queue, and reputation workflow foundation.',
            'packages' => ['opendkim', 'opendkim-tools', 'rspamd'],
            'services' => ['opendkim', 'rspamd'],
            'ports' => [],
        ],
        'email-marketing' => [
            'name' => 'Email Marketing',
            'category' => 'Email',
            'description' => 'Campaign/list management integration point for a future mailer module.',
            'packages' => [],
            'services' => [],
            'ports' => [],
        ],
        'file-manager' => [
            'name' => 'File Manager',
            'category' => 'Files',
            'description' => 'Managed file browser/edit operations under the site root.',
            'packages' => ['zip', 'unzip', 'acl'],
            'services' => [],
            'ports' => [],
        ],
        'php' => [
            'name' => 'PHP Management',
            'category' => 'Runtime',
            'description' => 'PHP-FPM version/package tracking and site runtime assignment.',
            'packages' => ['php-cli', 'php-fpm', 'php-mysql', 'php-xml', 'php-mbstring', 'php-curl', 'php-zip', 'php-bcmath', 'php-gd', 'php-intl'],
            'services' => ['php-fpm'],
            'ports' => [],
        ],
        'firewall' => [
            'name' => 'Firewall',
            'category' => 'Security',
            'description' => 'UFW/firewall rule inventory with queued allow/deny actions.',
            'packages' => ['ufw'],
            'services' => ['ufw'],
            'ports' => [],
        ],
        'backups' => [
            'name' => 'Backups & Restores',
            'category' => 'Backup',
            'description' => 'Local backup plans, restore inventory, and backup helper scripts.',
            'packages' => ['rsync', 'tar', 'gzip', 'restic', 'borgbackup'],
            'services' => [],
            'ports' => [],
        ],
        'docker' => [
            'name' => 'Docker Manager',
            'category' => 'Containers',
            'description' => 'Docker package/service module and container inventory.',
            'packages' => ['docker.io', 'docker-compose-plugin'],
            'services' => ['docker'],
            'ports' => [],
        ],
        'packages' => [
            'name' => 'Package Manager',
            'category' => 'System',
            'description' => 'APT package install/update workflow exposed through queued, whitelisted tasks.',
            'packages' => [],
            'services' => [],
            'ports' => [],
        ],
        'plugins' => [
            'name' => 'Plugin Manager',
            'category' => 'System',
            'description' => 'Plugin discovery/installer foundation for panel extensions.',
            'packages' => [],
            'services' => [],
            'ports' => [],
        ],
        'web-terminal' => [
            'name' => 'Web Terminal',
            'category' => 'System',
            'description' => 'Real-time task console foundation backed by queue output streaming.',
            'packages' => [],
            'services' => [],
            'ports' => [],
        ],
        'tuning' => [
            'name' => 'Server Tuning',
            'category' => 'System',
            'description' => 'Kernel, PHP-FPM, MariaDB, and web-server tuning integration point.',
            'packages' => ['sysstat'],
            'services' => ['sysstat'],
            'ports' => [],
        ],
        'high-availability' => [
            'name' => 'High Availability',
            'category' => 'Cluster',
            'description' => 'Cluster/replication planning surface for future multi-node deployments.',
            'packages' => ['rsync'],
            'services' => [],
            'ports' => [],
        ],
        'monitoring' => [
            'name' => 'Server Status & Logs',
            'category' => 'Monitoring',
            'description' => 'Server load, service health, process, and log viewing foundation.',
            'packages' => ['sysstat', 'htop', 'iotop'],
            'services' => ['sysstat'],
            'ports' => [],
        ],
        'ai-scanner' => [
            'name' => 'Security Scanner',
            'category' => 'Security',
            'description' => 'Malware/security scanner integration point for future AI-assisted scans.',
            'packages' => ['clamav', 'clamav-daemon'],
            'services' => ['clamav-daemon'],
            'ports' => [],
        ],
        'bandwidth' => [
            'name' => 'Bandwidth Accounting',
            'category' => 'Monitoring',
            'description' => 'Monthly bandwidth reset and usage accounting foundation.',
            'packages' => ['vnstat'],
            'services' => ['vnstat'],
            'ports' => [],
        ],
        's3-backups' => [
            'name' => 'S3 Backups',
            'category' => 'Backup',
            'description' => 'Object-storage backup integration point using restic/rclone style targets.',
            'packages' => ['restic', 'rclone'],
            'services' => [],
            'ports' => [],
        ],
    ],

    'service_units' => [
        'nginx' => ['name' => 'Nginx', 'package' => 'nginx'],
        'mariadb' => ['name' => 'MariaDB', 'package' => 'mariadb-server'],
        'redis-server' => ['name' => 'Redis', 'package' => 'redis-server'],
        'supervisor' => ['name' => 'Supervisor', 'package' => 'supervisor'],
        'pdns' => ['name' => 'PowerDNS', 'package' => 'pdns-server'],
        'pure-ftpd' => ['name' => 'Pure-FTPd', 'package' => 'pure-ftpd'],
        'postfix' => ['name' => 'Postfix', 'package' => 'postfix'],
        'dovecot' => ['name' => 'Dovecot', 'package' => 'dovecot-imapd'],
        'opendkim' => ['name' => 'OpenDKIM', 'package' => 'opendkim'],
        'rspamd' => ['name' => 'Rspamd', 'package' => 'rspamd'],
        'docker' => ['name' => 'Docker', 'package' => 'docker.io'],
        'ufw' => ['name' => 'UFW Firewall', 'package' => 'ufw'],
        'vnstat' => ['name' => 'vnStat', 'package' => 'vnstat'],
        'sysstat' => ['name' => 'sysstat', 'package' => 'sysstat'],
        'clamav-daemon' => ['name' => 'ClamAV', 'package' => 'clamav-daemon'],
    ],
];
